In [8]:
documents = [
    'people watch campusx',
    'campusx watch campusx',
    'people write comment',
    'campusx write comment'
]

In [9]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np


In [10]:
vocab = list(set(" ".join(documents).split()))

word_to_index = {word: i for i, word in enumerate(vocab)}

In [11]:
def one_hot(word):
    vector = np.zeros(len(vocab))
    vector[word_to_index[word]] = 1
    return vector

In [12]:
print('Vocabulary:', vocab)
print("One_hot for 'people':", one_hot('people'))

Vocabulary: ['watch', 'people', 'comment', 'write', 'campusx']
One_hot for 'people': [0. 1. 0. 0. 0.]


In [13]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(documents)
print("Vocabulary:", cv.get_feature_names_out())
print("Bow Matrix:\n", X.toarray())

Vocabulary: ['campusx' 'comment' 'people' 'watch' 'write']
Bow Matrix:
 [[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]


In [16]:
cv = CountVectorizer(ngram_range=(2, 2))
X = cv.fit_transform(documents)

print("Bi-gram Vocabulary:", cv.get_feature_names_out())
print("Bi-gram Matrix:\n",X.toarray())

Bi-gram Vocabulary: ['campusx watch' 'campusx write' 'people watch' 'people write'
 'watch campusx' 'write comment']
Bi-gram Matrix:
 [[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]


In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x = tfidf.fit_transform(documents)

print("Vocabulary:", tfidf.get_feature_names_out())
print("tfidf Matrix:\n", X.toarray())

Vocabulary: ['campusx' 'comment' 'people' 'watch' 'write']
tfidf Matrix:
 [[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]
